name: Build ELFReader packages.
on: [push]
jobs:
  pyinstaller-build-windows:
    runs-on: windows-latest
    steps:
      - name: Create Windows Executable
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: '3.11'
          spec: 'src/elfreader/__main__.py'
          requirements: 'requirements/run.txt'
          upload_exe_with_name: 'elfreader-win.exe'
          options: --onefile, --name "elfreader", --console,
  pyinstaller-build-macos:
    runs-on: macos-latest
    steps:
      - name: Create MacOS Executable
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: '3.11'
          spec: 'src/elfreader/__main__.py'
          requirements: 'requirements/run.txt'
          upload_exe_with_name: 'elfreader-macos'
          options: --onefile, --name "elfreader", --console,
  pyinstaller-build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Create Linux Executable
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: '3.11'
          spec: 'src/elfreader/__main__.py'
          requirements: 'requirements/run.txt'
          upload_exe_with_name: 'elfreader-linux'
          options: --onefile, --name "elfreader", --console,
